name: Compilation on ubuntu-20.04 and ubuntu-22.04

on: [push, pull_request]

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake .
      - run: make
      - run: make test CTEST_OUTPUT_ON_FAILURE=TRUE