name: Compilation on ubuntu and windows

on: [push, pull_request]

jobs:
  os_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake .
      - run: cmake --build .
      - run: ctest